services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin001
      MONGO_INITDB_ROOT_PASSWORD: admin001
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
